const PROJECT = "/api/project";
const ADD_PROJECT_URL = PROJECT;
const EDIT_PROJECT_URL = PROJECT;
const PROJECT_ENABLE_URL = PROJECT;
const PROJECT_LIST_URL = PROJECT;
const DELETE_PROJECT_URL = PROJECT;

export default {
  ADD_PROJECT_URL,
  EDIT_PROJECT_URL,
  PROJECT_ENABLE_URL,
  PROJECT_LIST_URL,
  DELETE_PROJECT_URL
};
