const TRACKER = "/api/log";
const TRACKER_ADD = TRACKER;
const TRACKER_EDIT = TRACKER;
const TRACKER_LIST = TRACKER;
const TRACKER_DELETE = TRACKER;

export default {
  TRACKER_ADD,
  TRACKER_EDIT,
  TRACKER_LIST,
  TRACKER_DELETE,
};
